# Generated by Django 5.1.3 on 2024-11-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
